name: build_tag
on:
  workflow_call:
    inputs:
      tagname:
        required: true
        type: string
    secrets:
      VSCE_TOKEN:
        required: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            npm_config_arch: x64
          - os: windows-latest
            platform: win32
            arch: ia32
            npm_config_arch: ia32
          # - os: windows-latest
          #  platform: win32
          #  arch: arm64
          #  npm_config_arch: arm
          - os: ubuntu-latest
            platform: linux
            arch: x64
            npm_config_arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            npm_config_arch: arm64
          # - os: ubuntu-latest
          #  platform: linux
          #  arch: armhf
          #  npm_config_arch: arm
          - os: ubuntu-latest
            platform: alpine
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
            npm_config_arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tagname }}
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: npm --version
      - run: npm run install:all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_arch: ${{ matrix.npm_config_arch }}
      - run: npx vsce --version
      - shell: pwsh
        run: echo "target=${{ matrix.platform }}-${{ matrix.arch }}" >> $env:GITHUB_ENV
      - run: npx vsce package --target ${{ env.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.target }}
          path: "*.vsix"

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - uses: actions/download-artifact@v4
      - run: npx @vscode/vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
      - run: echo $(find . -iname *.vsix)
      - name: Github release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: |
            */*.vsix
            */*/*.vsix
          name: ${{ inputs.tagname }}
          tag_name: ${{ inputs.tagname }}
