name: build_tag
on:
  workflow_call:
    inputs:
      tagname:
        required: true
        type: string
    secrets:
      VSCE_TOKEN:
        required: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            vsce_target: win32-x64
            npm_config_arch: x64
          - os: windows-latest
            vsce_target: win32-arm64
            npm_config_arch: x64 # for now we use the win32 build
          - os: ubuntu-latest
            vsce_target: linux-x64
            npm_config_arch: x64
          - os: ubuntu-latest
            vsce_target: linux-arm64
            npm_config_arch: arm64
          # - os: ubuntu-latest
          #  platform: linux
          #  arch: armhf
          #  npm_config_arch: arm
          - os: ubuntu-latest
            vsce_target: alpine-x64
            npm_config_arch: x64
          - os: macos-latest
            vsce_target: darwin-x64
            npm_config_arch: x64
          - os: macos-latest
            vsce_target: darwin-arm64
            npm_config_arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tagname }}
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: npm --version
      - run: npm run install:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_arch: ${{ matrix.npm_config_arch }}
      - run: npx vsce --version
      - run: npx vsce package --target ${{ matrix.vsce_target }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.vsce_target }}
          path: "*.vsix"

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - uses: actions/download-artifact@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: npx @vscode/vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
      - run: echo $(find . -iname *.vsix)
      - name: Github release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: |
            */*.vsix
            */*/*.vsix
          name: ${{ inputs.tagname }}
          tag_name: ${{ inputs.tagname }}
